# Generated by Django 6.0.7 on 2026-08-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('H', 'Half day'), ('L', 'Late'), ('E', 'Excused')], default='P', max_length=1),
        ),
    ]
