# Generated by Django 6.0.7 on 2026-08-04 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.IntegerField()),
                ('term', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('content', models.JSONField(default=dict, help_text='Weeks -> strands/sub-strands plan')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.learningarea')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week', models.PositiveSmallIntegerField()),
                ('lesson_number', models.PositiveSmallIntegerField()),
                ('strand', models.CharField(max_length=100)),
                ('sub_strand', models.CharField(blank=True, max_length=100)),
                ('learning_outcomes', models.TextField()),
                ('resources', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='teachers.schemeofwork')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tsc_number', models.CharField(max_length=20, unique=True)),
                ('learning_areas', models.ManyToManyField(blank=True, related_name='teachers', to='assessments.learningarea')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Peer/HoD review sign-off', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schemes', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='teachers.teacher'),
        ),
        migrations.CreateModel(
            name='ProfessionalDevelopmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(blank=True, help_text='e.g. TSC, KICD', max_length=100)),
                ('completed_on', models.DateField()),
                ('tpd_points', models.PositiveSmallIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_records', to='teachers.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
