# Generated by Django 6.0.7 on 2026-08-04 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemeofwork',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='document',
            field=models.FileField(blank=True, help_text='Uploaded scheme document', null=True, upload_to='schemes/%Y/'),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin/head who approved or rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_schemes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Entered manually'), ('UPLOADED', 'Uploaded document'), ('GENERATED', 'AI generated')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='schemeofwork',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='schemeofwork',
            name='content',
            field=models.JSONField(blank=True, default=dict, help_text='Weeks -> strands/sub-strands plan'),
        ),
    ]
