# Generated by Django 6.0.7 on 2026-08-04 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0003_teacherattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='employment_type',
            field=models.CharField(choices=[('TSC', 'Government (TSC)'), ('PNP', 'PNP (Govt intern programme)'), ('BOM', 'BOM employed'), ('PTA', 'PTA employed')], default='TSC', max_length=4),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('HEAD', 'Head Teacher'), ('DEPUTY', 'Deputy Head Teacher'), ('SENIOR', 'Senior Teacher'), ('TEACHER', 'Teacher'), ('INTERN', 'Intern Teacher')], default='TEACHER', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tsc_number',
            field=models.CharField(help_text='TSC number, or a school payroll no for BOM/PTA', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='SupportStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('BURSAR', 'Bursar / Accounts'), ('SECRETARY', 'Secretary / Admin'), ('KITCHEN', 'Kitchen staff'), ('CLEANER', 'Cleaner'), ('SECURITY', 'Security'), ('DRIVER', 'Driver'), ('NURSE', 'School nurse'), ('LIBRARIAN', 'Librarian'), ('GROUNDS', 'Grounds keeper'), ('OTHER', 'Other')], max_length=10)),
                ('title', models.CharField(blank=True, help_text='Rank/title, e.g. Head Cook, Chief Security Officer', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('employment_type', models.CharField(choices=[('BOM', 'BOM employed'), ('PTA', 'PTA employed'), ('CONTRACT', 'Contracted'), ('COUNTY', 'County/Government')], default='BOM', max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'support staff',
            },
        ),
    ]
