# Generated by Django 6.0.7 on 2026-08-05 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0004_teacher_employment_type_teacher_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportstaff',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Values for admin-defined staff columns'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Values for admin-defined staff columns'),
        ),
        migrations.CreateModel(
            name='StaffField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50)),
                ('key', models.SlugField()),
                ('applies_to', models.CharField(choices=[('ALL', 'All staff'), ('TEACHING', 'Teaching staff'), ('NON_TEACHING', 'Non-teaching staff')], default='ALL', max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('school', 'key'), name='unique_staff_field_key')],
            },
        ),
    ]
