# Generated by Django 6.0.7 on 2026-08-05 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0005_supportstaff_extra_teacher_extra_stafffield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportstaff',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Who this staff member reports to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervises_support', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Portal login for this staff member (role SUPPORT)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Who this teacher reports to for submissions and approvals', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervises_teachers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'duties',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StaffReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('period', models.CharField(blank=True, help_text='e.g. Term 2 2026, June', max_length=60)),
                ('body', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='reports/%Y/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('RETURNED', 'Returned for changes')], default='DRAFT', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_to_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
