# Generated by Django 6.0.7 on 2026-08-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_supportstaff_supervisor_supportstaff_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportstaff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
    ]
