# Generated by Django 6.0.7 on 2026-08-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_staffmessage_stafftask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonplan',
            options={'ordering': ['week', 'lesson_number']},
        ),
        migrations.AlterModelOptions(
            name='professionaldevelopmentrecord',
            options={'ordering': ['-completed_on', 'id']},
        ),
        migrations.AlterModelOptions(
            name='schemeofwork',
            options={'ordering': ['-year', '-term', 'grade', 'id']},
        ),
        migrations.AlterModelOptions(
            name='supportstaff',
            options={'ordering': ['category', 'full_name', 'id'], 'verbose_name_plural': 'support staff'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['user__first_name', 'user__last_name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='teacherattendance',
            options={'ordering': ['-date', 'id']},
        ),
    ]
