# Generated by Django 6.0.7 on 2026-08-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_peerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafffield',
            name='field_type',
            field=models.CharField(choices=[('TEXT', 'Free text'), ('CHOICE', 'Pick from choices')], default='TEXT', max_length=6),
        ),
        migrations.AddField(
            model_name='stafffield',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supportstaff',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
