# Generated by Django 6.0.7 on 2026-08-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_stafffield_field_type_stafffield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phase',
            field=models.CharField(blank=True, choices=[('PRE_PRIMARY', 'Pre-Primary'), ('PRIMARY', 'Primary'), ('JUNIOR', 'Junior School')], max_length=12),
        ),
    ]
