# Generated by Django 6.0.7 on 2026-08-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='MoE school code', max_length=30, unique=True)),
                ('kemis_code', models.CharField(blank=True, max_length=30)),
                ('level', models.CharField(choices=[('PRIMARY', 'Primary'), ('JSS', 'Junior School'), ('SSS', 'Senior School'), ('COMPOSITE', 'Composite')], default='JSS', max_length=10)),
                ('county', models.CharField(max_length=50)),
                ('subcounty', models.CharField(blank=True, max_length=50)),
                ('paybill_account_prefix', models.CharField(blank=True, help_text='Prefix parents put before the admission number when paying via paybill', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
