# Generated by Django 6.0.7 on 2026-08-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='accommodation',
            field=models.CharField(blank=True, choices=[('DAY', 'Day'), ('BOARDING', 'Boarding'), ('DAY_BOARDING', 'Day & Boarding')], max_length=12),
        ),
        migrations.AddField(
            model_name='school',
            name='category',
            field=models.CharField(blank=True, choices=[('NATIONAL', 'National'), ('EXTRA_COUNTY', 'Extra-County'), ('COUNTY', 'County'), ('SUB_COUNTY', 'Sub-County')], help_text='MoE placement tier (national / extra-county / county / sub-county)', max_length=12),
        ),
        migrations.AddField(
            model_name='school',
            name='gender',
            field=models.CharField(blank=True, choices=[('MIXED', 'Mixed'), ('BOYS', 'Boys'), ('GIRLS', 'Girls')], max_length=6),
        ),
        migrations.AddField(
            model_name='school',
            name='ownership',
            field=models.CharField(blank=True, choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('FAITH', 'Faith-based / Sponsored')], max_length=8),
        ),
        migrations.AddField(
            model_name='school',
            name='ward',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='school',
            name='zone',
            field=models.CharField(blank=True, help_text='Education zone / administrative location', max_length=60),
        ),
    ]
