# Generated by Django 6.0.7 on 2026-08-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
