# Generated by Django 6.0.7 on 2026-08-10 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_contact_email_school_contact_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='school',
            name='postal_address',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='school',
            name='vote_heads',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='SchoolDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('REGISTRATION', 'Registration & licences'), ('POLICY', 'School policies'), ('CIRCULAR', 'MoE circulars'), ('BOARD', 'Board & committee minutes'), ('FINANCE', 'Finance & audit'), ('SAFETY', 'Health & safety'), ('TEMPLATE', 'Forms & templates'), ('OTHER', 'Other')], default='OTHER', max_length=14)),
                ('file', models.FileField(upload_to='school_documents/%Y/')),
                ('note', models.TextField(blank=True)),
                ('document_date', models.DateField(blank=True, help_text='The date on the document itself', null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', '-document_date', '-created_at', 'id'],
            },
        ),
    ]
