# Generated by Django 6.0.7, then hand-edited to backfill before the unique
# constraint applies (existing rows would otherwise collide on the empty slug).

from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    School = apps.get_model("schools", "School")
    used = set()
    for school in School.objects.all().order_by("id"):
        base = slugify(school.name)[:50] or f"school-{school.code}".lower()
        candidate = base
        n = 2
        while candidate in used or School.objects.filter(slug=candidate).exclude(pk=school.pk).exists():
            candidate = f"{base}-{n}"
            n += 1
        school.slug = candidate
        used.add(candidate)
        school.save(update_fields=["slug"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0006_school_alt_phone_school_logo_school_motto_and_more"),
    ]

    operations = [
        # 1. Add the column with NO index. A SlugField defaults to
        #    db_index=True, which on Postgres also creates a "<col>_like" index;
        #    step 3 would then try to create that same _like index again and fail
        #    with DuplicateTable. db_index=False keeps step 1 index-free so the
        #    unique index (and its _like companion) are created exactly once.
        migrations.AddField(
            model_name="school",
            name="slug",
            field=models.SlugField(blank=True, db_index=False, default="", max_length=60),
        ),
        # 2. Give every existing school a unique slug from its name.
        migrations.RunPython(backfill_slugs, noop),
        # 3. Now enforce uniqueness (creates the unique index + its _like index).
        migrations.AlterField(
            model_name="school",
            name="slug",
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
