# Generated by Django 6.0.7 on 2026-08-05 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('schools', '0002_alter_school_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('action', models.CharField(choices=[('SCORE_CHANGED', 'Mark changed'), ('LEARNER_DEACTIVATED', 'Learner deactivated'), ('LEARNER_REACTIVATED', 'Learner reactivated'), ('LEARNER_ADMITTED', 'Learner admitted'), ('LEARNERS_IMPORTED', 'Learners imported'), ('STAFF_DEACTIVATED', 'Staff deactivated'), ('STAFF_ADDED', 'Staff added'), ('REPORT_REVIEWED', 'Staff report reviewed'), ('SCHEME_REVIEWED', 'Scheme of work reviewed'), ('PROMOTION_APPLIED', 'Promotion applied'), ('PROMOTION_REVERSED', 'Promotion reversed'), ('RIGHTS_GRANTED', 'Admission rights granted'), ('RIGHTS_WITHDRAWN', 'Admission rights withdrawn'), ('PASSWORD_RESET', 'Password reset by admin'), ('PAYMENT_RECORDED', 'Payment recorded')], max_length=24)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=40)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'audit entries',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['school', '-created_at'], name='common_audi_school__ffb4be_idx'), models.Index(fields=['action'], name='common_audi_action_d2ab57_idx')],
            },
        ),
    ]
