# Generated by Django 6.0.7 on 2026-08-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auditentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='action',
            field=models.CharField(choices=[('SCORE_CHANGED', 'Mark changed'), ('LEARNER_DEACTIVATED', 'Learner deactivated'), ('LEARNER_REACTIVATED', 'Learner reactivated'), ('LEARNER_ADMITTED', 'Learner admitted'), ('LEARNERS_IMPORTED', 'Learners imported'), ('STAFF_DEACTIVATED', 'Staff deactivated'), ('STAFF_ADDED', 'Staff added'), ('REPORT_REVIEWED', 'Staff report reviewed'), ('SCHEME_REVIEWED', 'Scheme of work reviewed'), ('PROMOTION_APPLIED', 'Promotion applied'), ('PROMOTION_REVERSED', 'Promotion reversed'), ('RIGHTS_GRANTED', 'Admission rights granted'), ('RIGHTS_WITHDRAWN', 'Admission rights withdrawn'), ('PASSWORD_RESET', 'Password reset by admin'), ('PAYMENT_RECORDED', 'Payment recorded'), ('SCHOOL_PROVISIONED', 'School provisioned'), ('SUBSCRIPTION_INVOICED', 'Subscription invoiced'), ('SUBSCRIPTION_PAID', 'Subscription paid'), ('SUBSCRIPTION_STATUS', 'Subscription status changed')], max_length=24),
        ),
    ]
