# Generated by Django 6.0.7 on 2026-08-05 07:48

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0005_supportstaff_extra_teacher_extra_stafffield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('facility_type', models.CharField(choices=[('KITCHEN', 'Kitchen & Dining Hall'), ('HEALTH', 'Health / Sick Bay'), ('TRANSPORT', 'Transport (Buses)'), ('DORMITORY', 'Dormitory'), ('LAB', 'Science Laboratory'), ('ICT', 'Computer Lab / ICT'), ('LIBRARY', 'Library'), ('SPORTS', 'Sports & Games'), ('FARM', 'Farm / Agriculture'), ('WORKSHOP', 'Workshop / Technical'), ('HOME_SCI', 'Home Science Room'), ('STORE', 'Stores'), ('SANITATION', 'Water & Sanitation'), ('GROUNDS', 'Grounds & Maintenance'), ('ADMIN', 'Administration Block'), ('STAFFROOM', 'Staff Room'), ('OTHER', 'Other')], max_length=12)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Beds, seats, passengers — whatever fits this facility', null=True)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'ordering': ['facility_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(help_text='Role at this facility', max_length=80)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='facilities.facility')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('support_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_assignments', to='teachers.supportstaff')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facility_assignments', to='teachers.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=100)),
                ('unit', models.CharField(default='pcs', help_text='kg, litres, pcs, cartons', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Restock when the quantity falls to this level', max_digits=10)),
                ('last_restocked', models.DateField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='facilities.facility')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'supplies',
                'ordering': ['item'],
            },
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_facility_name'),
        ),
    ]
