# Generated by Django 6.0.7 on 2026-08-05 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facilitycategory'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitycategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='facilitycategory',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school'),
        ),
        migrations.CreateModel(
            name='NavSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='facilitycategory',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Sidebar heading this category sits under; blank = Facilities', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='facilities.navsection'),
        ),
        migrations.AddConstraint(
            model_name='navsection',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_nav_section'),
        ),
    ]
