# Generated by Django 6.0.7 on 2026-08-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facilitycategory_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilityassignment',
            options={'ordering': ['position', 'id']},
        ),
    ]
