# Generated by Django 6.0.7 on 2026-08-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='smsmessage',
            options={'ordering': ['-created_at', 'id']},
        ),
    ]
