# Generated by Django 6.0.7 on 2026-08-05 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_announcement_options_alter_smsmessage_options'),
        ('schools', '0002_alter_school_options'),
        ('students', '0008_learner_exit_date_learner_exit_note_learner_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='students.guardian')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_messages', to='students.learner')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_parent_messages', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(help_text='The staff side of this thread', on_delete=django.db.models.deletion.CASCADE, related_name='parent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
