# Generated by Django 6.0.7 on 2026-08-10 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_parentmessage'),
        ('schools', '0005_school_contact_email_school_contact_phone'),
        ('students', '0009_admissionright_grades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='SMS', max_length=8),
        ),
        migrations.CreateModel(
            name='MessageBlast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField(help_text='Supports {name} {learner} {class} {balance} {school}')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='SMS', max_length=8)),
                ('audience', models.CharField(choices=[('SCHOOL', 'Every parent'), ('GRADE', 'One class'), ('UNPAID', 'Parents with a fee balance'), ('LEARNER', "One learner's parents")], max_length=8)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('stream', models.CharField(blank=True, max_length=20)),
                ('recipients', models.PositiveIntegerField(default=0)),
                ('learner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blasts', to='students.learner')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_blasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='blast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.messageblast'),
        ),
    ]
