# Generated by Django 6.0.7 on 2026-08-18 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_smsmessage_channel_messageblast_smsmessage_blast'),
        ('schools', '0007_school_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsmessage',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smsmessages', to='schools.school'),
        ),
    ]
