# Generated by Django 6.0.7 on 2026-08-06 18:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_alter_school_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('price_per_learner', models.DecimalField(decimal_places=2, help_text='Charge per active learner, per term (KES)', max_digits=8)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Floor for a term's bill, however few learners", max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('trial_days', models.PositiveSmallIntegerField(default=30, help_text='Free-trial length for a newly provisioned school')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price_per_learner', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('FEATURE', 'New feature'), ('UPDATE', 'Update'), ('MAINTENANCE', 'Maintenance'), ('BILLING', 'Billing'), ('OTHER', 'Notice')], default='UPDATE', max_length=12)),
                ('link', models.URLField(blank=True, help_text="Optional 'read more' link")),
                ('published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='TRIAL', max_length=10)),
                ('trial_ends_on', models.DateField(blank=True, null=True)),
                ('paid_through', models.DateField(blank=True, null=True)),
                ('grace_days', models.PositiveSmallIntegerField(default=14)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_created', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='platform.plan')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='schools.school')),
            ],
            options={
                'ordering': ['school__name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_label', models.CharField(help_text='e.g. Term 2 2026', max_length=60)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(help_text='Access is paid through this date once the invoice is paid')),
                ('learner_count', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PAID', 'Paid'), ('VOID', 'Void')], default='SENT', max_length=6)),
                ('issued_on', models.DateField(default=django.utils.timezone.localdate)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='M-Pesa code, bank ref, cheque no…', max_length=100)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_marked', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='platform.subscription')),
            ],
            options={
                'ordering': ['-issued_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_receipts', to=settings.AUTH_USER_MODEL)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='platform.platformannouncement')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('announcement', 'user'), name='one_receipt_per_admin')],
            },
        ),
    ]
