# Generated by Django 6.0.7 on 2026-08-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_reminder_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
