# Generated by Django 6.0.7 on 2026-08-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('schools', '0001_initial'),
        ('teachers', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.IntegerField()),
                ('stream', models.CharField(blank=True, max_length=20)),
                ('lessons_per_week', models.PositiveSmallIntegerField(default=5)),
                ('needs_lab', models.BooleanField(default=False)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.learningarea')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'teacher', 'learning_area', 'grade', 'stream'), name='unique_lesson_requirement')],
            },
        ),
    ]
