# Generated by Django 6.0.7 on 2026-08-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_lessonrequirement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['day', 'period__number', 'grade', 'stream']},
        ),
        migrations.AlterModelOptions(
            name='lessonrequirement',
            options={'ordering': ['grade', 'stream', 'id']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name']},
        ),
    ]
