"""AI scheme-of-work generation via the Claude API.

With ANTHROPIC_API_KEY (or an `ant auth login` profile) configured, schemes are
generated by Claude with a JSON schema-constrained response. Without
credentials, a deterministic KICD-style template is produced instead so the
whole upload -> generate -> review flow works offline. Either way the result
lands in SchemeOfWork.content with status PENDING for the head to review.
"""

import os

SCHEME_JSON_SCHEMA = {
    "type": "object",
    "properties": {
        "weeks": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "week": {"type": "integer"},
                    "lessons": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "lesson": {"type": "integer"},
                                "strand": {"type": "string"},
                                "sub_strand": {"type": "string"},
                                "learning_outcomes": {
                                    "type": "array", "items": {"type": "string"}
                                },
                                "learning_experiences": {"type": "string"},
                                "key_inquiry_question": {"type": "string"},
                                "resources": {"type": "string"},
                                "assessment_methods": {"type": "string"},
                            },
                            "required": [
                                "lesson", "strand", "sub_strand", "learning_outcomes",
                                "learning_experiences", "key_inquiry_question",
                                "resources", "assessment_methods",
                            ],
                            "additionalProperties": False,
                        },
                    },
                },
                "required": ["week", "lessons"],
                "additionalProperties": False,
            },
        },
    },
    "required": ["weeks"],
    "additionalProperties": False,
}


def _ai_configured() -> bool:
    return bool(os.getenv("ANTHROPIC_API_KEY"))


def _stub_scheme(learning_area: str, grade: int, weeks: int, lessons_per_week: int) -> dict:
    """Deterministic KICD-shaped template for offline/dev use."""
    return {
        "weeks": [
            {
                "week": week,
                "lessons": [
                    {
                        "lesson": lesson,
                        "strand": f"{learning_area} strand (week {week})",
                        "sub_strand": f"Sub-strand {week}.{lesson}",
                        "learning_outcomes": [
                            f"By the end of the lesson the learner should be able to "
                            f"demonstrate competency {week}.{lesson} in {learning_area}."
                        ],
                        "learning_experiences": (
                            "Learners discuss, practise and present in groups."
                        ),
                        "key_inquiry_question": (
                            f"How do we apply {learning_area} concepts from week {week}?"
                        ),
                        "resources": "MoE-approved course book, charts, digital devices",
                        "assessment_methods": "Observation, oral questions, written exercise",
                    }
                    for lesson in range(1, lessons_per_week + 1)
                ],
            }
            for week in range(1, weeks + 1)
        ],
        "generator": "template-stub (no ANTHROPIC_API_KEY configured)",
    }


def generate_scheme(
    *, learning_area: str, grade: int, term: int, year: int,
    weeks: int = 10, lessons_per_week: int = 4, extra_instructions: str = "",
) -> dict:
    if not _ai_configured():
        return _stub_scheme(learning_area, grade, weeks, lessons_per_week)

    import anthropic

    client = anthropic.Anthropic()
    prompt = (
        f"Create a scheme of work for the Kenyan Competency-Based Curriculum (CBC).\n"
        f"Learning area: {learning_area}\n"
        f"Grade: {grade}\n"
        f"Term: {term}, Year: {year}\n"
        f"Plan {weeks} weeks with {lessons_per_week} lessons per week.\n"
        f"Follow KICD curriculum designs for this learning area and grade: use real "
        f"strands and sub-strands in the order they appear in the curriculum design, "
        f"specific lesson-level learning outcomes ('By the end of the lesson the "
        f"learner should be able to...'), learner-centred learning experiences, key "
        f"inquiry questions, locally available resources, and CBC-appropriate "
        f"assessment methods.\n"
        + (f"Additional instructions from the teacher: {extra_instructions}\n"
           if extra_instructions else "")
    )
    response = client.messages.create(
        model="claude-opus-5",
        max_tokens=16000,
        system=(
            "You are a Kenyan CBC curriculum specialist who writes schemes of work "
            "that align with KICD curriculum designs and are ready for head-teacher "
            "review."
        ),
        messages=[{"role": "user", "content": prompt}],
        output_config={"format": {"type": "json_schema", "schema": SCHEME_JSON_SCHEMA}},
    )
    if response.stop_reason == "refusal":
        raise RuntimeError("The model declined to generate this scheme.")

    import json

    text = next(block.text for block in response.content if block.type == "text")
    scheme = json.loads(text)
    scheme["generator"] = response.model
    return scheme
