# Generated by Django 6.0.7 on 2026-08-05 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_alter_assessment_options_alter_learningarea_options_and_more'),
        ('schools', '0002_alter_school_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('authority', models.CharField(choices=[('MOE', 'Ministry of Education'), ('KICD', 'Kenya Institute of Curriculum Development'), ('KNEC', 'Kenya National Examinations Council'), ('TSC', 'Teachers Service Commission'), ('COUNTY', 'County education office'), ('SCHOOL', 'School document'), ('OTHER', 'Other reference')], default='OTHER', max_length=10)),
                ('publisher', models.CharField(blank=True, max_length=150)),
                ('url', models.URLField(blank=True)),
                ('effective_date', models.DateField(blank=True, help_text='When this source took effect', null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('kind', models.CharField(choices=[('DESIGN', 'Curriculum design'), ('POLICY', 'Policy / circular'), ('TEXTBOOK', 'Approved course book'), ('GUIDE', 'Teacher guide'), ('BANK', 'Assessment / question bank'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('grades', models.JSONField(blank=True, default=list, help_text='Grades it applies to, e.g. [7, 8, 9]')),
                ('file', models.FileField(blank=True, null=True, upload_to='curriculum/%Y/')),
                ('text', models.TextField(blank=True, help_text='Extracted or pasted text — this is what gets indexed')),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('learning_area', models.ForeignKey(blank=True, help_text='Leave blank if the document spans subjects', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='assessments.learningarea')),
                ('school', models.ForeignKey(blank=True, help_text='Leave blank for a national document shared by all schools', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='schools.school')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='knowledge.source')),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveIntegerField()),
                ('heading', models.CharField(blank=True, max_length=250)),
                ('text', models.TextField()),
                ('term_counts', models.JSONField(blank=True, default=dict)),
                ('length', models.PositiveIntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.document')),
            ],
            options={
                'ordering': ['document_id', 'ordinal'],
                'constraints': [models.UniqueConstraint(fields=('document', 'ordinal'), name='unique_chunk_ordinal')],
            },
        ),
    ]
