# Generated by Django 6.0.7 on 2026-08-17 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_assessment_kind'),
        ('knowledge', '0001_initial'),
        ('schools', '0006_school_alt_phone_school_logo_school_motto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('VIDEO', 'Video lesson'), ('BOOK', 'Book / textbook'), ('NOTES', 'Notes / revision'), ('PAPER', 'Past paper / quiz'), ('SIMULATION', 'Simulation / interactive'), ('LINK', 'Web resource')], default='VIDEO', max_length=12)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('topic', models.CharField(blank=True, help_text='Strand / sub-strand or topic, for search', max_length=200)),
                ('grades', models.JSONField(blank=True, default=list, help_text='Grades it suits, e.g. [7, 8]')),
                ('url', models.URLField(blank=True, help_text='YouTube link, or a link to a book/resource')),
                ('file', models.FileField(blank=True, null=True, upload_to='elearning/%Y/')),
                ('author', models.CharField(blank=True, max_length=150)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_resources_added', to=settings.AUTH_USER_MODEL)),
                ('learning_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_resources', to='assessments.learningarea')),
                ('school', models.ForeignKey(blank=True, help_text='Leave blank for a national resource shared by all schools', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='schools.school')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_resources', to='knowledge.source')),
            ],
            options={
                'ordering': ['learning_area__name', 'title', 'id'],
            },
        ),
    ]
