# Generated by Django 6.0.7 on 2026-08-05 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_alter_school_options'),
        ('students', '0008_learner_exit_date_learner_exit_note_learner_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_year', models.PositiveSmallIntegerField()),
                ('to_year', models.PositiveSmallIntegerField()),
                ('grade', models.IntegerField(blank=True, help_text='Limit to one grade; blank = whole school', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft — previewed, not applied'), ('APPLIED', 'Applied'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=8)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_runs_applied', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_runs_created', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_runs_reversed', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'ordering': ['-year'],
                'constraints': [models.UniqueConstraint(fields=('school', 'year'), name='one_academic_year_per_school'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('school',), name='one_current_academic_year')],
            },
        ),
        migrations.CreateModel(
            name='PromotionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('PROMOTE', 'Move up a grade'), ('REPEAT', 'Repeat the year'), ('TRANSFER', 'Transferred to another school'), ('GRADUATE', 'Completed Grade 12')], default='PROMOTE', max_length=8)),
                ('to_grade', models.IntegerField(blank=True, null=True)),
                ('to_stream', models.CharField(blank=True, max_length=20)),
                ('pathway_track', models.CharField(blank=True, max_length=60)),
                ('pathway_rationale', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('previous_grade', models.IntegerField(blank=True, null=True)),
                ('previous_stream', models.CharField(blank=True, max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=12)),
                ('previous_active', models.BooleanField(blank=True, null=True)),
                ('applied', models.BooleanField(default=False)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_outcomes', to='students.learner')),
                ('pathway', models.ForeignKey(blank=True, help_text='Senior School pathway, set at the Grade 9 to 10 transition', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.pathway')),
                ('previous_pathway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.pathway')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='promotions.promotionrun')),
            ],
            options={
                'ordering': ['learner__grade', 'learner__admission_number'],
                'constraints': [models.UniqueConstraint(fields=('run', 'learner'), name='one_outcome_per_learner_per_run')],
            },
        ),
    ]
