# Generated by Django 6.0.7 on 2026-08-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'School Admin'), ('TEACHER', 'Teacher'), ('SUPPORT', 'Support staff'), ('PARENT', 'Parent/Guardian')], default='TEACHER', max_length=10),
        ),
    ]
