# Generated by Django 6.0.7 on 2026-08-04 14:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('grades', models.JSONField(default=list, help_text='Grades where offered, e.g. [7, 8, 9]')),
                ('pathway', models.ForeignKey(blank=True, help_text='Set for Senior School pathway-specific areas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.pathway')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('CAT1', 'CAT 1'), ('CAT2', 'CAT 2'), ('ENDTERM', 'End of Term Exam'), ('FORMATIVE', 'Formative/Classroom Assessment')], max_length=10)),
                ('grade', models.IntegerField()),
                ('stream', models.CharField(blank=True, max_length=20)),
                ('term', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('year', models.PositiveSmallIntegerField()),
                ('max_marks', models.PositiveSmallIntegerField(default=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('rubric', models.JSONField(blank=True, default=list, help_text='Optional override bands, e.g. [[80, "EE"], [60, "ME"], [40, "AE"], [0, "BE"]]')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.learningarea')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('competency_level', models.CharField(choices=[('EE', 'Exceeding Expectation'), ('ME', 'Meeting Expectation'), ('AE', 'Approaching Expectation'), ('BE', 'Below Expectation')], editable=False, max_length=2)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.assessment')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.learner')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('school', 'kind', 'learning_area', 'grade', 'stream', 'term', 'year'), name='unique_assessment_slot'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('assessment', 'learner'), name='one_score_per_learner_per_assessment'),
        ),
    ]
