# Generated by Django 6.0.7 on 2026-08-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-year', '-term', 'grade', 'id']},
        ),
        migrations.AlterModelOptions(
            name='learningarea',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['learner_id', 'id']},
        ),
    ]
