# Generated by Django 6.0.7 on 2026-08-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_assessment_options_alter_learningarea_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='kind',
            field=models.CharField(choices=[('CAT1', 'CAT 1'), ('CAT2', 'CAT 2'), ('RAT', 'RAT'), ('MIDTERM', 'Midterm Exam'), ('ENDTERM', 'Final Exam'), ('FORMATIVE', 'Formative/Classroom Assessment')], max_length=10),
        ),
    ]
