import { useCallback, useEffect, useState } from 'react'
import { apiGet, apiUpload, apiWrite } from './api.js'
import { gradeLabel } from './format.js'

const STATUS_BADGE = {
  DRAFT: 'queued',
  PENDING: 'queued',
  APPROVED: 'online',
  REJECTED: 'offline',
}
const STATUS_LABEL = {
  DRAFT: 'Draft',
  PENDING: 'Pending review',
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
}

export function StatusBadge({ status }) {
  return (
    <span className={`badge ${STATUS_BADGE[status] || 'queued'}`}>
      {STATUS_LABEL[status] || status}
    </span>
  )
}

export function SchemeWeeks({ content }) {
  if (!content?.weeks?.length) return <p className="muted">No structured content.</p>
  return (
    <div>
      {content.generator && <p className="muted">Generated by: {content.generator}</p>}
      <table>
        <thead>
          <tr>
            <th>Wk</th><th>Strand / Sub-strand</th><th>Learning outcomes</th>
            <th>Inquiry question</th><th>Assessment</th>
          </tr>
        </thead>
        <tbody>
          {content.weeks.flatMap((week) =>
            week.lessons.map((lesson) => (
              <tr key={`${week.week}-${lesson.lesson}`}>
                <td>{week.week}.{lesson.lesson}</td>
                <td>
                  {lesson.strand}
                  <div className="muted">{lesson.sub_strand}</div>
                </td>
                <td>{(lesson.learning_outcomes || []).join(' ')}</td>
                <td>{lesson.key_inquiry_question}</td>
                <td>{lesson.assessment_methods}</td>
              </tr>
            )),
          )}
        </tbody>
      </table>
    </div>
  )
}

// Teacher-facing tab: upload a scheme document or generate one with AI.
export default function TeacherSchemes({ summary, onRefresh }) {
  // Only offer subjects this teacher actually teaches — the backend rejects
  // schemes of work for anything else.
  const [areas, setAreas] = useState(summary.taught_learning_areas || [])
  const [message, setMessage] = useState('')
  const [busy, setBusy] = useState(false)
  const [form, setForm] = useState({ learning_area: '', grade: 7, term: 2, year: 2026, weeks: 10 })
  const [file, setFile] = useState(null)

  useEffect(() => {
    if (summary.taught_learning_areas) {
      setAreas(summary.taught_learning_areas)
    } else {
      apiGet('/api/learning-areas/').then((d) => setAreas(d.results || d))
    }
  }, [summary])

  const setField = (key) => (e) => setForm((f) => ({ ...f, [key]: e.target.value }))

  async function upload(e) {
    e.preventDefault()
    if (!file || !form.learning_area) {
      setMessage('Pick a learning area and a file first.')
      return
    }
    setBusy(true)
    const fd = new FormData()
    fd.append('learning_area', form.learning_area)
    fd.append('grade', form.grade)
    fd.append('term', form.term)
    fd.append('year', form.year)
    fd.append('document', file)
    const result = await apiUpload('/api/schemes-of-work/', fd)
    setBusy(false)
    setMessage(result.ok
      ? 'Uploaded — sent to the head teacher for review.'
      : `Upload failed: ${JSON.stringify(result.data)}`)
    if (result.ok) {
      setFile(null)
      onRefresh()
    }
  }

  async function generate() {
    if (!form.learning_area) {
      setMessage('Pick a learning area first.')
      return
    }
    setBusy(true)
    setMessage('Generating scheme of work…')
    const result = await apiWrite('/api/schemes-of-work/generate/', {
      learning_area: Number(form.learning_area),
      grade: Number(form.grade),
      term: Number(form.term),
      year: Number(form.year),
      weeks: Number(form.weeks),
      lessons_per_week: 4,
    })
    setBusy(false)
    setMessage(result.ok
      ? 'Scheme generated — sent to the head teacher for review.'
      : `Generation failed: ${JSON.stringify(result.data)}`)
    if (result.ok) onRefresh()
  }

  const schemes = summary.schemes_of_work

  return (
    <div>
      <div className="card">
        <h3>New scheme of work</h3>
        <p>
          <select value={form.learning_area} onChange={setField('learning_area')}>
            <option value="">Learning area…</option>
            {areas.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}
          </select>{' '}
          Grade <input type="number" min="1" max="12" style={{ width: '4rem' }}
            value={form.grade} onChange={setField('grade')} />{' '}
          Term <input type="number" min="1" max="3" style={{ width: '3.5rem' }}
            value={form.term} onChange={setField('term')} />{' '}
          Year <input type="number" style={{ width: '5rem' }}
            value={form.year} onChange={setField('year')} />{' '}
          Weeks <input type="number" min="1" max="14" style={{ width: '4rem' }}
            value={form.weeks} onChange={setField('weeks')} />
        </p>
        <form onSubmit={upload} style={{ display: 'flex', gap: '0.75rem', alignItems: 'center', flexWrap: 'wrap' }}>
          <input type="file" accept=".pdf,.doc,.docx,.xls,.xlsx" data-testid="scheme-file"
            onChange={(e) => setFile(e.target.files[0] || null)} />
          <button className="primary" type="submit" disabled={busy}>Upload for review</button>
          <span className="muted">or</span>
          <button className="primary" type="button" onClick={generate} disabled={busy}>
            {busy ? 'Working…' : 'Generate with AI'}
          </button>
        </form>
        {message && <p className="muted">{message}</p>}
      </div>

      <div className="card">
        <h3>My schemes</h3>
        {schemes.length === 0 && <p className="muted">No schemes yet.</p>}
        {schemes.length > 0 && (
          <table>
            <thead>
              <tr>
                <th>Learning area</th><th>Class</th><th>Term</th><th>Source</th>
                <th>Status</th><th>Feedback</th>
              </tr>
            </thead>
            <tbody>
              {schemes.map((s) => (
                <tr key={s.id}>
                  <td>{s.learning_area}</td>
                  <td>{gradeLabel(s.grade)}</td>
                  <td>T{s.term} {s.year}</td>
                  <td>
                    {s.source === 'GENERATED' ? 'AI generated'
                      : s.source === 'UPLOADED' ? 'Uploaded' : 'Manual'}
                    {s.document && (
                      <>
                        {' '}
                        <a href={s.document} target="_blank" rel="noreferrer">file</a>
                      </>
                    )}
                  </td>
                  <td><StatusBadge status={s.status} /></td>
                  <td className="muted">{s.review_comment}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  )
}
