import { useEffect, useState } from 'react'
import { apiGet, apiUpload, apiWrite } from './api.js'
import { gradeLabel } from './format.js'
import { PickList, Trail, count } from './portalUi.jsx'

const STATUS_BADGE = {
  DRAFT: 'queued',
  PENDING: 'queued',
  APPROVED: 'online',
  REJECTED: 'offline',
}
const STATUS_LABEL = {
  DRAFT: 'Draft',
  PENDING: 'Pending review',
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
}

export function StatusBadge({ status }) {
  return (
    <span className={`badge ${STATUS_BADGE[status] || 'queued'}`}>
      {STATUS_LABEL[status] || status}
    </span>
  )
}

export function SchemeWeeks({ content }) {
  if (!content?.weeks?.length) return <p className="muted">No structured content.</p>
  return (
    <div>
      {content.generator && <p className="muted">Generated by: {content.generator}</p>}
      <table>
        <thead>
          <tr>
            <th>Wk</th><th>Strand / Sub-strand</th><th>Learning outcomes</th>
            <th>Inquiry question</th><th>Assessment</th>
          </tr>
        </thead>
        <tbody>
          {content.weeks.flatMap((week) =>
            week.lessons.map((lesson) => (
              <tr key={`${week.week}-${lesson.lesson}`}>
                <td>{week.week}.{lesson.lesson}</td>
                <td>
                  {lesson.strand}
                  <div className="muted">{lesson.sub_strand}</div>
                </td>
                <td>{(lesson.learning_outcomes || []).join(' ')}</td>
                <td>{lesson.key_inquiry_question}</td>
                <td>{lesson.assessment_methods}</td>
              </tr>
            )),
          )}
        </tbody>
      </table>
    </div>
  )
}

/** The grades this teacher works in — from their timetable, the assessments
 * they mark, and any schemes they already wrote. */
export function taughtGrades(summary) {
  const grades = new Set([
    ...(summary.timetable || []).map((l) => l.grade),
    ...(summary.assessments || []).map((a) => a.grade),
    ...(summary.schemes_of_work || []).map((s) => s.grade),
  ])
  return [...grades].filter(Boolean).sort((a, b) => a - b)
}

// Teacher-facing tab: pick the class, then the learning area, then work on
// that combination's schemes — upload a document or generate one with AI.
export default function TeacherSchemes({ summary, onRefresh }) {
  // Only offer subjects this teacher actually teaches — the backend rejects
  // schemes of work for anything else.
  const [areas, setAreas] = useState(summary.taught_learning_areas || [])
  const [grade, setGrade] = useState(null)
  const [areaId, setAreaId] = useState(null)
  const [message, setMessage] = useState('')
  const [busy, setBusy] = useState(false)
  const [form, setForm] = useState({ term: 2, year: 2026, weeks: 10 })
  const [file, setFile] = useState(null)

  useEffect(() => {
    if (summary.taught_learning_areas) {
      setAreas(summary.taught_learning_areas)
    } else {
      apiGet('/api/learning-areas/').then((d) => setAreas(d.results || d))
    }
  }, [summary])

  const setField = (key) => (e) => setForm((f) => ({ ...f, [key]: e.target.value }))
  const area = areas.find((a) => a.id === areaId)
  const schemes = summary.schemes_of_work
  const grades = taughtGrades(summary)
  const gradeOptions = (grades.length ? grades : Array.from({ length: 12 }, (_, i) => i + 1))
    .map((g) => ({
      key: String(g),
      label: gradeLabel(g),
      hint: count(schemes.filter((s) => s.grade === g).length, 'scheme'),
    }))
  const areaOptions = areas.map((a) => ({
    key: String(a.id),
    label: a.name,
    hint: count(
      schemes.filter((s) => s.grade === grade && s.learning_area === a.name).length,
      'scheme',
    ),
  }))
  const mine = schemes.filter((s) => s.grade === grade && s.learning_area === area?.name)

  const crumbs = [
    'Classes',
    ...(grade ? [gradeLabel(grade)] : []),
    ...(area ? [area.name] : []),
  ]
  const backTo = (i) => {
    if (i < 1) setGrade(null)
    setAreaId(null)
    setMessage('')
  }

  async function upload(e) {
    e.preventDefault()
    if (!file) {
      setMessage('Pick a file first.')
      return
    }
    setBusy(true)
    const fd = new FormData()
    fd.append('learning_area', areaId)
    fd.append('grade', grade)
    fd.append('term', form.term)
    fd.append('year', form.year)
    fd.append('document', file)
    const result = await apiUpload('/api/schemes-of-work/', fd)
    setBusy(false)
    setMessage(result.ok
      ? 'Uploaded — sent to the head teacher for review.'
      : `Upload failed: ${JSON.stringify(result.data)}`)
    if (result.ok) {
      setFile(null)
      onRefresh()
    }
  }

  async function generate() {
    setBusy(true)
    setMessage('Generating scheme of work…')
    const result = await apiWrite('/api/schemes-of-work/generate/', {
      learning_area: Number(areaId),
      grade: Number(grade),
      term: Number(form.term),
      year: Number(form.year),
      weeks: Number(form.weeks),
      lessons_per_week: 4,
    })
    setBusy(false)
    setMessage(result.ok
      ? 'Scheme generated — sent to the head teacher for review.'
      : `Generation failed: ${JSON.stringify(result.data)}`)
    if (result.ok) onRefresh()
  }

  if (!grade || !area) {
    return (
      <div className="card">
        {crumbs.length > 1 && <Trail crumbs={crumbs} onCrumb={backTo} />}
        {!grade && (
          <PickList prompt="Choose the class." options={gradeOptions}
            onPick={(k) => setGrade(Number(k))} />
        )}
        {grade && (
          <PickList prompt="Choose the learning area." options={areaOptions}
            onPick={(k) => setAreaId(Number(k))} />
        )}
      </div>
    )
  }

  return (
    <div>
      <div className="card">
        <Trail crumbs={crumbs} onCrumb={backTo} />
        <h3>New scheme — {area.name}, {gradeLabel(grade)}</h3>
        <p>
          Term <input type="number" min="1" max="3" style={{ width: '3.5rem' }}
            value={form.term} onChange={setField('term')} />{' '}
          Year <input type="number" style={{ width: '5rem' }}
            value={form.year} onChange={setField('year')} />{' '}
          Weeks <input type="number" min="1" max="14" style={{ width: '4rem' }}
            value={form.weeks} onChange={setField('weeks')} />
        </p>
        <form onSubmit={upload} style={{ display: 'flex', gap: '0.75rem', alignItems: 'center', flexWrap: 'wrap' }}>
          <input type="file" accept=".pdf,.doc,.docx,.xls,.xlsx" data-testid="scheme-file"
            onChange={(e) => setFile(e.target.files[0] || null)} />
          <button className="primary" type="submit" disabled={busy}>Upload for review</button>
          <span className="muted">or</span>
          <button className="primary" type="button" onClick={generate} disabled={busy}>
            {busy ? 'Working…' : 'Generate with AI'}
          </button>
        </form>
        {message && <p className="muted">{message}</p>}
      </div>

      <div className="card">
        <h3>My schemes — {area.name}, {gradeLabel(grade)}</h3>
        {mine.length === 0 && <p className="muted">No schemes for this class yet.</p>}
        {mine.length > 0 && (
          <table>
            <thead>
              <tr>
                <th>Term</th><th>Source</th><th>Status</th><th>Feedback</th>
              </tr>
            </thead>
            <tbody>
              {mine.map((s) => (
                <tr key={s.id}>
                  <td>T{s.term} {s.year}</td>
                  <td>
                    {s.source === 'GENERATED' ? 'AI generated'
                      : s.source === 'UPLOADED' ? 'Uploaded' : 'Manual'}
                    {s.document && (
                      <>
                        {' '}
                        <a href={s.document} target="_blank" rel="noreferrer">file</a>
                      </>
                    )}
                  </td>
                  <td><StatusBadge status={s.status} /></td>
                  <td className="muted">{s.review_comment}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  )
}
