import { useEffect, useState } from 'react'
import { apiGet, apiUpload, apiWrite } from './api.js'
import { gradeLabel } from './format.js'
import { PickList, Trail, count } from './portalUi.jsx'

const STATUS_BADGE = {
  DRAFT: 'queued',
  PENDING: 'queued',
  APPROVED: 'online',
  REJECTED: 'offline',
}
const STATUS_LABEL = {
  DRAFT: 'Draft',
  PENDING: 'Pending review',
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
}

export function StatusBadge({ status }) {
  return (
    <span className={`badge ${STATUS_BADGE[status] || 'queued'}`}>
      {STATUS_LABEL[status] || status}
    </span>
  )
}

export function SchemeWeeks({ content }) {
  if (!content?.weeks?.length) return <p className="muted">No structured content.</p>
  return (
    <div>
      {content.generator && <p className="muted">Generated by: {content.generator}</p>}
      <table>
        <thead>
          <tr>
            <th>Wk</th><th>Strand / Sub-strand</th><th>Learning outcomes</th>
            <th>Inquiry question</th><th>Assessment</th>
          </tr>
        </thead>
        <tbody>
          {content.weeks.flatMap((week) =>
            week.lessons.map((lesson) => (
              <tr key={`${week.week}-${lesson.lesson}`}>
                <td>{week.week}.{lesson.lesson}</td>
                <td>
                  {lesson.strand}
                  <div className="muted">{lesson.sub_strand}</div>
                </td>
                <td>{(lesson.learning_outcomes || []).join(' ')}</td>
                <td>{lesson.key_inquiry_question}</td>
                <td>{lesson.assessment_methods}</td>
              </tr>
            )),
          )}
        </tbody>
      </table>
    </div>
  )
}

/** The grades this teacher works in — from their timetable, the assessments
 * they mark, and any schemes they already wrote. */
export function taughtGrades(summary) {
  const grades = new Set([
    ...(summary.timetable || []).map((l) => l.grade),
    ...(summary.assessments || []).map((a) => a.grade),
    ...(summary.schemes_of_work || []).map((s) => s.grade),
  ])
  return [...grades].filter(Boolean).sort((a, b) => a - b)
}

/** Read a scheme before anyone else does — the generated weeks in full, and a
 * way to open or download an uploaded document. */
function SchemePreview({ scheme, onClose, onEdit, onSubmit, busy }) {
  const weeks = scheme.content?.weeks || []
  return (
    <div className="card">
      <div className="page-header" style={{ marginBottom: '0.3rem' }}>
        <h3 style={{ margin: 0 }}>
          {scheme.learning_area} — {gradeLabel(scheme.grade)} · Term {scheme.term} {scheme.year}
        </h3>
        <span style={{ display: 'flex', gap: '0.4rem', flexWrap: 'wrap' }}>
          {scheme.document && (
            <a className="grade-chip" href={scheme.document}
              target="_blank" rel="noreferrer">Open the document</a>
          )}
          {scheme.document && (
            <a className="grade-chip" href={scheme.document} download>Download</a>
          )}
          {weeks.length > 0 && scheme.status !== 'APPROVED' && (
            <button onClick={onEdit}>Edit</button>
          )}
          {scheme.status !== 'PENDING' && scheme.status !== 'APPROVED' && (
            <button className="primary" onClick={onSubmit} disabled={busy}>
              {busy ? 'Sending…' : 'Submit for review'}
            </button>
          )}
          <button onClick={onClose}>Close</button>
        </span>
      </div>
      <p className="muted">
        <StatusBadge status={scheme.status} />{' '}
        {scheme.status === 'DRAFT'
          ? 'Yours to check and change. The head teacher sees it once you submit it.'
          : scheme.status === 'PENDING'
            ? 'With the head teacher for review.'
            : scheme.status === 'REJECTED'
              ? `Returned: ${scheme.review_comment || 'see the head teacher.'}`
              : 'Approved — ask the head teacher to return it before changing it.'}
      </p>
      {scheme.document && weeks.length === 0 && (
        <p className="muted">
          This scheme is an uploaded document — open it above to proofread it.
        </p>
      )}
      <SchemeWeeks content={scheme.content} />
    </div>
  )
}

/** Edit the generated plan lesson by lesson, before it goes for review. */
function SchemeEditor({ scheme, onCancel, onSaved, onMessage }) {
  const [weeks, setWeeks] = useState(
    JSON.parse(JSON.stringify(scheme.content?.weeks || [])),
  )
  const [busy, setBusy] = useState(false)

  const setLesson = (wi, li, key, value) =>
    setWeeks((prev) => prev.map((w, i) => (i !== wi ? w : {
      ...w,
      lessons: w.lessons.map((l, j) => (j !== li ? l : { ...l, [key]: value })),
    })))

  async function save() {
    setBusy(true)
    const res = await apiWrite(`/api/schemes-of-work/${scheme.id}/`,
      { content: { ...scheme.content, weeks } }, { method: 'PATCH' })
    setBusy(false)
    if (res.ok) {
      onMessage('Scheme updated.')
      onSaved()
    } else {
      onMessage(res.data?.detail || 'Could not save your changes.')
    }
  }

  return (
    <div className="card">
      <div className="page-header" style={{ marginBottom: '0.3rem' }}>
        <h3 style={{ margin: 0 }}>
          Editing — {scheme.learning_area} {gradeLabel(scheme.grade)} T{scheme.term}
        </h3>
        <span style={{ display: 'flex', gap: '0.4rem' }}>
          <button className="primary" onClick={save} disabled={busy}>
            {busy ? 'Saving…' : 'Save changes'}
          </button>
          <button onClick={onCancel}>Cancel</button>
        </span>
      </div>
      <table>
        <thead>
          <tr>
            <th>Wk</th><th>Strand</th><th>Sub-strand</th>
            <th>Learning outcomes</th><th>Inquiry question</th><th>Assessment</th>
          </tr>
        </thead>
        <tbody>
          {weeks.flatMap((week, wi) => week.lessons.map((lesson, li) => (
            <tr key={`${wi}-${li}`}>
              <td className="muted">{week.week}.{lesson.lesson}</td>
              <td><input value={lesson.strand || ''} style={{ width: '9rem' }}
                onChange={(e) => setLesson(wi, li, 'strand', e.target.value)} /></td>
              <td><input value={lesson.sub_strand || ''} style={{ width: '9rem' }}
                onChange={(e) => setLesson(wi, li, 'sub_strand', e.target.value)} /></td>
              <td>
                <textarea rows="2" style={{ width: '14rem' }}
                  value={(lesson.learning_outcomes || []).join('\n')}
                  onChange={(e) => setLesson(
                    wi, li, 'learning_outcomes',
                    e.target.value.split('\n').filter(Boolean),
                  )} />
              </td>
              <td><input value={lesson.key_inquiry_question || ''} style={{ width: '11rem' }}
                onChange={(e) => setLesson(wi, li, 'key_inquiry_question', e.target.value)} /></td>
              <td><input value={lesson.assessment_methods || ''} style={{ width: '10rem' }}
                onChange={(e) => setLesson(wi, li, 'assessment_methods', e.target.value)} /></td>
            </tr>
          )))}
        </tbody>
      </table>
    </div>
  )
}

// Teacher-facing tab: pick the class, then the learning area, then work on
// that combination's schemes — upload a document or generate one with AI.
export default function TeacherSchemes({ summary, onRefresh }) {
  // Only offer subjects this teacher actually teaches — the backend rejects
  // schemes of work for anything else.
  const [areas, setAreas] = useState(summary.taught_learning_areas || [])
  const [grade, setGrade] = useState(null)
  const [areaId, setAreaId] = useState(null)
  const [message, setMessage] = useState('')
  const [busy, setBusy] = useState(false)
  const [form, setForm] = useState({ term: 2, year: 2026, weeks: 10 })
  const [file, setFile] = useState(null)
  const [open, setOpen] = useState(null)   // scheme being proofread
  const [editing, setEditing] = useState(null) // scheme being edited

  useEffect(() => {
    if (summary.taught_learning_areas) {
      setAreas(summary.taught_learning_areas)
    } else {
      apiGet('/api/learning-areas/').then((d) => setAreas(d.results || d))
    }
  }, [summary])

  const setField = (key) => (e) => setForm((f) => ({ ...f, [key]: e.target.value }))
  const area = areas.find((a) => a.id === areaId)
  const schemes = summary.schemes_of_work
  const grades = taughtGrades(summary)
  const gradeOptions = (grades.length ? grades : Array.from({ length: 12 }, (_, i) => i + 1))
    .map((g) => ({
      key: String(g),
      label: gradeLabel(g),
      hint: count(schemes.filter((s) => s.grade === g).length, 'scheme'),
    }))
  const areaOptions = areas.map((a) => ({
    key: String(a.id),
    label: a.name,
    hint: count(
      schemes.filter((s) => s.grade === grade && s.learning_area === a.name).length,
      'scheme',
    ),
  }))
  const mine = schemes.filter((s) => s.grade === grade && s.learning_area === area?.name)

  const crumbs = [
    'Classes',
    ...(grade ? [gradeLabel(grade)] : []),
    ...(area ? [area.name] : []),
  ]
  const backTo = (i) => {
    if (i < 1) setGrade(null)
    setAreaId(null)
    setMessage('')
  }

  async function upload(e) {
    e.preventDefault()
    if (!file) {
      setMessage('Pick a file first.')
      return
    }
    setBusy(true)
    const fd = new FormData()
    fd.append('learning_area', areaId)
    fd.append('grade', grade)
    fd.append('term', form.term)
    fd.append('year', form.year)
    fd.append('document', file)
    const result = await apiUpload('/api/schemes-of-work/', fd)
    setBusy(false)
    setMessage(result.ok
      ? 'Uploaded — open it to check it is the right file, then submit it.'
      : `Upload failed: ${JSON.stringify(result.data)}`)
    if (result.ok) {
      setFile(null)
      onRefresh()
    }
  }

  async function submit(scheme) {
    setBusy(true)
    const res = await apiWrite(`/api/schemes-of-work/submit/${scheme.id}/`, {})
    setBusy(false)
    setMessage(res.ok
      ? 'Sent to the head teacher for review.'
      : res.data?.detail || 'Could not submit it.')
    if (res.ok) { setOpen(null); onRefresh() }
  }

  async function generate() {
    setBusy(true)
    setMessage('Generating scheme of work…')
    const result = await apiWrite('/api/schemes-of-work/generate/', {
      learning_area: Number(areaId),
      grade: Number(grade),
      term: Number(form.term),
      year: Number(form.year),
      weeks: Number(form.weeks),
      lessons_per_week: 4,
    })
    setBusy(false)
    setMessage(result.ok
      ? 'Draft ready — proofread and edit it, then submit it for review.'
      : `Generation failed: ${JSON.stringify(result.data)}`)
    if (result.ok) onRefresh()
  }

  // Proofreading and editing take over the panel — one job at a time.
  if (editing) {
    return (
      <SchemeEditor
        scheme={editing}
        onCancel={() => setEditing(null)}
        onSaved={() => { setEditing(null); setOpen(null); onRefresh() }}
        onMessage={setMessage}
      />
    )
  }
  if (open) {
    const current = schemes.find((s) => s.id === open.id) || open
    return (
      <SchemePreview
        scheme={current}
        busy={busy}
        onClose={() => setOpen(null)}
        onEdit={() => setEditing(current)}
        onSubmit={() => submit(current)}
      />
    )
  }

  if (!grade || !area) {
    return (
      <div className="card">
        {crumbs.length > 1 && <Trail crumbs={crumbs} onCrumb={backTo} />}
        {!grade && (
          <PickList prompt="Choose the class." options={gradeOptions}
            onPick={(k) => setGrade(Number(k))} />
        )}
        {grade && (
          <PickList prompt="Choose the learning area." options={areaOptions}
            onPick={(k) => setAreaId(Number(k))} />
        )}
      </div>
    )
  }

  return (
    <div>
      <div className="card">
        <Trail crumbs={crumbs} onCrumb={backTo} />
        <h3>New scheme — {area.name}, {gradeLabel(grade)}</h3>
        <p>
          Term <input type="number" min="1" max="3" style={{ width: '3.5rem' }}
            value={form.term} onChange={setField('term')} />{' '}
          Year <input type="number" style={{ width: '5rem' }}
            value={form.year} onChange={setField('year')} />{' '}
          Weeks <input type="number" min="1" max="14" style={{ width: '4rem' }}
            value={form.weeks} onChange={setField('weeks')} />
        </p>
        <form onSubmit={upload} style={{ display: 'flex', gap: '0.75rem', alignItems: 'center', flexWrap: 'wrap' }}>
          <input type="file" accept=".pdf,.doc,.docx,.xls,.xlsx" data-testid="scheme-file"
            onChange={(e) => setFile(e.target.files[0] || null)} />
          <button className="primary" type="submit" disabled={busy}>Upload for review</button>
          <span className="muted">or</span>
          <button className="primary" type="button" onClick={generate} disabled={busy}>
            {busy ? 'Working…' : 'Generate with AI'}
          </button>
        </form>
        {message && <p className="muted">{message}</p>}
      </div>

      <div className="card">
        <h3>My schemes — {area.name}, {gradeLabel(grade)}</h3>
        {mine.length === 0 && <p className="muted">No schemes for this class yet.</p>}
        {mine.length > 0 && (
          <table>
            <thead>
              <tr>
                <th>Term</th><th>Source</th><th>Status</th><th>Feedback</th><th></th>
              </tr>
            </thead>
            <tbody>
              {mine.map((s) => (
                <tr key={s.id}>
                  <td>T{s.term} {s.year}</td>
                  <td>
                    {s.source === 'GENERATED' ? 'AI generated'
                      : s.source === 'UPLOADED' ? 'Uploaded' : 'Manual'}
                  </td>
                  <td><StatusBadge status={s.status} /></td>
                  <td className="muted">{s.review_comment}</td>
                  <td style={{ whiteSpace: 'nowrap' }}>
                    {/* Proofread, change, hand in — the three things a teacher
                        needs to do with a plan before the head sees it. */}
                    <button onClick={() => setOpen(s)}>Proofread</button>{' '}
                    {s.content?.weeks?.length > 0 && s.status !== 'APPROVED' && (
                      <><button onClick={() => setEditing(s)}>Edit</button>{' '}</>
                    )}
                    {s.document && (
                      <><a className="grade-chip" href={s.document} download>Download</a>{' '}</>
                    )}
                    {s.status !== 'PENDING' && s.status !== 'APPROVED' && (
                      <button className="primary" onClick={() => submit(s)} disabled={busy}>
                        Submit
                      </button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  )
}
