# Generated by Django 6.0.7 on 2026-08-04 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('STEM', 'STEM'), ('SOCIAL', 'Social Sciences'), ('ARTS_SPORTS', 'Arts & Sports Science')], max_length=15, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(help_text='MSISDN, e.g. 2547XXXXXXXX — SMS and M-Pesa anchor', max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(blank=True, max_length=30)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upi', models.CharField(blank=True, help_text='NEMIS/KEMIS Unique Personal Identifier', max_length=20)),
                ('admission_number', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('grade', models.IntegerField(choices=[(1, 'G1'), (2, 'G2'), (3, 'G3'), (4, 'G4'), (5, 'G5'), (6, 'G6'), (7, 'G7'), (8, 'G8'), (9, 'G9'), (10, 'G10'), (11, 'G11'), (12, 'G12')])),
                ('stream', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('guardians', models.ManyToManyField(blank=True, related_name='learners', to='students.guardian')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('pathway', models.ForeignKey(blank=True, help_text='Assigned at Grade 9 -> 10 transition', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.pathway')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'admission_number'), name='unique_admission_per_school')],
            },
        ),
    ]
