# Generated by Django 6.0.7 on 2026-08-04 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0002_guardian_user'),
        ('teachers', '0002_remove_schemeofwork_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='grade',
            field=models.IntegerField(choices=[(-1, 'PP1'), (0, 'PP2'), (1, 'G1'), (2, 'G2'), (3, 'G3'), (4, 'G4'), (5, 'G5'), (6, 'G6'), (7, 'G7'), (8, 'G8'), (9, 'G9'), (10, 'G10'), (11, 'G11'), (12, 'G12')]),
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.IntegerField(choices=[(-1, 'PP1'), (0, 'PP2'), (1, 'G1'), (2, 'G2'), (3, 'G3'), (4, 'G4'), (5, 'G5'), (6, 'G6'), (7, 'G7'), (8, 'G8'), (9, 'G9'), (10, 'G10'), (11, 'G11'), (12, 'G12')])),
                ('stream', models.CharField(blank=True, max_length=20)),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_groups', to='teachers.teacher')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'grade', 'stream'), name='unique_class_group')],
            },
        ),
    ]
