# Generated by Django 6.0.7 on 2026-08-05 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0003_alter_learner_grade_classgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Values for admin-defined learner columns'),
        ),
        migrations.CreateModel(
            name='LearnerField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50)),
                ('key', models.SlugField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('school', 'key'), name='unique_learner_field_key')],
            },
        ),
    ]
