# Generated by Django 6.0.7 on 2026-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_learner_extra_learnerfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classgroup',
            name='grade',
            field=models.IntegerField(choices=[(-2, 'PG'), (-1, 'PP1'), (0, 'PP2'), (1, 'G1'), (2, 'G2'), (3, 'G3'), (4, 'G4'), (5, 'G5'), (6, 'G6'), (7, 'G7'), (8, 'G8'), (9, 'G9'), (10, 'G10'), (11, 'G11'), (12, 'G12')]),
        ),
        migrations.AlterField(
            model_name='learner',
            name='grade',
            field=models.IntegerField(choices=[(-2, 'PG'), (-1, 'PP1'), (0, 'PP2'), (1, 'G1'), (2, 'G2'), (3, 'G3'), (4, 'G4'), (5, 'G5'), (6, 'G6'), (7, 'G7'), (8, 'G8'), (9, 'G9'), (10, 'G10'), (11, 'G11'), (12, 'G12')]),
        ),
    ]
