# Generated by Django 6.0.7 on 2026-08-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_classgroup_grade_alter_learner_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={'ordering': ['grade', 'stream']},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={'ordering': ['full_name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='learner',
            options={'ordering': ['grade', 'stream', 'admission_number']},
        ),
        migrations.AlterModelOptions(
            name='pathway',
            options={'ordering': ['code']},
        ),
    ]
