# Generated by Django 6.0.7 on 2026-08-05 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_options'),
        ('students', '0006_alter_classgroup_options_alter_guardian_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='guardian',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='guardian',
            name='is_primary_contact',
            field=models.BooleanField(default=False, help_text='The first person the school calls'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='national_id',
            field=models.CharField(blank=True, help_text='ID / passport number', max_length=20),
        ),
        migrations.AddField(
            model_name='guardian',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='learner',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='admission_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='admitted_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who completed the admission form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learners_admitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learner',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='birth_certificate_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='learner',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AddField(
            model_name='learner',
            name='bus_route',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='learner',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='e.g. asthma, epilepsy, sickle cell'),
        ),
        migrations.AddField(
            model_name='learner',
            name='county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='learner',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='learner',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='learner',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='learner',
            name='home_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='learner',
            name='immunisation_up_to_date',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='medication',
            field=models.TextField(blank=True, help_text='Regular medication and dosage'),
        ),
        migrations.AddField(
            model_name='learner',
            name='nationality',
            field=models.CharField(blank=True, default='Kenyan', max_length=50),
        ),
        migrations.AddField(
            model_name='learner',
            name='nhif_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='learner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='learner_photos/'),
        ),
        migrations.AddField(
            model_name='learner',
            name='previous_grade',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='learner',
            name='previous_school',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='learner',
            name='religion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='learner',
            name='residence',
            field=models.CharField(choices=[('DAY', 'Day scholar'), ('BOARDER', 'Boarder')], default='DAY', max_length=8),
        ),
        migrations.AddField(
            model_name='learner',
            name='special_needs',
            field=models.TextField(blank=True, help_text='Learning support, mobility, vision, hearing'),
        ),
        migrations.AddField(
            model_name='learner',
            name='subcounty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='learner',
            name='transfer_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='learner',
            name='transport',
            field=models.CharField(blank=True, choices=[('WALK', 'Walks'), ('BUS', 'School bus'), ('PRIVATE', 'Private/parent drop-off'), ('PUBLIC', 'Public transport')], max_length=8),
        ),
        migrations.AddField(
            model_name='learner',
            name='ward',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='AdmissionRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, help_text='e.g. Grade 1 intake, January 2027', max_length=200)),
                ('expires_on', models.DateField(blank=True, help_text='Leave blank for no expiry', null=True)),
                ('active', models.BooleanField(default=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_rights_granted', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_rights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('school', 'user'), name='one_admission_right_per_staff')],
            },
        ),
    ]
