# Generated by Django 6.0.7 on 2026-08-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_guardian_address_guardian_alt_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='exit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='exit_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='learner',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('TRANSFERRED', 'Transferred out'), ('GRADUATED', 'Completed Grade 12'), ('WITHDRAWN', 'Withdrawn')], default='ENROLLED', max_length=12),
        ),
    ]
