# Generated by Django 6.0.7 on 2026-08-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_learner_exit_date_learner_exit_note_learner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionright',
            name='grades',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
