# Generated by Django 6.0.7 on 2026-08-17 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_school_alt_phone_school_logo_school_motto_and_more'),
        ('students', '0009_admissionright_grades'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='learner',
            index=models.Index(fields=['school', 'upi'], name='learner_school_upi_idx'),
        ),
    ]
