# Generated by Django 6.0.7 on 2026-08-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
